from enum import Enum


class CurrencyErrorMessages(Enum):
    CURRENCY_DOES_NOT_EXIST_ERROR = "CURRENCY_DOES_NOT_EXIST_ERROR"
    WRONG_CURRENCY_CODE_ERROR = "WRONG_CURRENCY_CODE_ERROR"
    CURRENCY_ALREADY_EXISTS_ERROR = "CURRENCY_ALREADY_EXISTS_ERROR"
    WRONG_CURRENCY_NAME_ERROR = "WRONG_CURRENCY_NAME_ERROR"
    YOU_ARE_NOT_ALLOWED_TO_EDIT_ERROR = " YOU_ARE_NOT_ALLOWED_TO_EDIT_ERROR"
