# Generated by Django 3.2.5 on 2021-08-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
    ]
