# Generated by Django 3.2.5 on 2021-08-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_walletbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletbalance',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
